version: '3'

services:
  server-nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
